version: "3"
services:
  database:
    image: postgres:13-alpine
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - google-podcasts-db-data:/var/lib/postgresql/data/
      
volumes:
  google-podcasts-db-data: